[tool.pytest.ini_options]
testpaths = ["src"]
python_files = ["task_*.py"]
python_functions = ["task_*"]

[project]
name = "browser-task-automation"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.3",
    "pytest-playwright>=0.7.2",
    "python-dotenv>=1.2.2",
]
